version: '3'

# Define services
services:

  # App Service
  app:
    container_name: ad-mediation-api
    # Configuration for building the docker image for the service
    build:
      context: . # Use an image built from the specified dockerfile in the current directory.
      dockerfile: Dockerfile
    ports:
      - "8080:8080" # Forward the exposed port 8080 on the container to port 8080 on the host machine
    restart: unless-stopped
    depends_on: 
      - mongo # This service depends on mongo. Start that first.
    environment: # Pass environment variables to the service
      PERSISTENT_STORAGE: MongoDB
      MONGO_URL: mongo:27017
    networks: # Networks to join (Services on the same network can communicate with each other using their name)
      - backend
    volumes:
      - "~/Development/logs/ad-mediation:/app/logs"

  # Mongo Service   
  mongo:
    image: 'mongo:latest'
    container_name: 'mongo'
    ports:
      - '27017:27017'
    networks:
      - backend

networks:
  backend:  